### ISSUE TITLE
Erroneous works property on Work entities

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary-client#41]
```yml
entities-affected: 1136
examples:
  - url: https://openlibrary.org/works/OL67142W.json?v=2
mongo-queries:
  - name: Affected works
    query: """db.getCollection('works').find({ works: {$exists: true} })"""
dump: ol_dump_works_2017-98-31
```

Based on the above example, it looks like these were introduced by `WorkBot` ~2009. In the above, example, the revision is given the comment "add subject: Piano", so these should be added to `subjects`.
https://openlibrary.org/works/OL67142W?m=history

Looked through the main codebase, and can find no reference of the `works` property on a `Work`, so they should be safe to correct.

- [x] Generate list of work keys to change
- [x] Add all `works` to `subjects`
