### ISSUE TITLE
Remove number_of_editions property on Work entities

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary-client#42]
```yml
entities-affected: 7418
examples:
  - url: https://openlibrary.org/works/OL15558210W.json
mongo-queries:
  - name: Affected works
    query: """db.getCollection('works').find({ number_of_editions: {$exists: true} })"""
dump: ol_dump_works_2017-98-31
```

This property appears on some works, but does not appear to be in sync with the actual state of the work. Should be removed.

Looks like was originally introduced by `EdwardBot` in some edition merging code: https://github.com/internetarchive/openlibrary/search?utf8=%E2%9C%93&q=number_of_editions

Those files should (probably?) also be updated, although they do appear inactive.

- [x] Generate list of work keys to update
- [x] Remove all instances of `number_of_editions` property
- [x] Create issues for removing all references in internetarchive/openlibrary to `number_of_editions`
