### ISSUE TITLE
Work subjects are sometimes objects

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary-client#66]
```yml
entities-affected: 10
examples:
  - url: https://openlibrary.org/works/OL167326W.json
mongo-queries:
  - name: Affected works
    query: """db.works.find({ subjects: {$type: "object"} })"""
dump: ol_dump_works_2017-11-30
```

- [x] Generate list of work keys to update
- [x] Fix affected works
- [x] Create issue for analyzing/removing references in internetarchive/openlibrary to subject objects
