### ISSUE TITLE
Work.subject_people are sometimes objects instead of string

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary-client#67]
Some `subject_people` have the form `{ type: "/type/text", value: String }` instead of just plain strings.

```yml
entities-affected: 403
examples:
  - url: https://openlibrary.org/works/OL55497W.json
mongo-queries:
  - name: Affected works
    query: """db.works.find({ subject_people: {$type: "object"} }, {key: 1, subject_people: 1, _id: 0})"""
dump: ol_dump_works_2017-11-30
```

- [x] Generate list of work keys to update
- [x] Fix affected works
- [x] Create issue for analyzing/removing references in internetarchive/openlibrary
