### ISSUE TITLE
CI (Continuous Integration) breaks for mac

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary-client#93]
Suggesting dropping support/check until CI is fixed

Current instructions (which are to removed from .travis.yml):
```
matrix:
  include:
    - language: generic
      python: 3.6
      os: osx
      before_install:
        - brew update; brew install python3 yaz
        - virtualenv ~/env -p python3
        - source ~/env/bin/activate
        - pip install pytest
```

Possibly relevant:
https://gist.github.com/timhodson/033f635421628cc9361f
